baseURL = 'https://sensational-rugelach-b0be35.netlify.app/'
languageCode = 'en-us'
title = 'Lorem Ipsum'


[params]
  favicon = "/assets/img/favicon.png"
  appleIcon = "/assets/img/apple-touch-icon.png"
  mainLogo = "/assets/img/logo.png"
  darkLogo = "/assets/img/logo-dark.png"